name: Commit Changes

on:
  push:
    branches:
      - main

jobs:
  commit_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"

      - name: Fazer alteração de exemplo
        run: |
          echo "Some new changes" >> file.txt
          git add file.txt

      - name: Criar commit com mensagem dinâmica
        run: |
          commit_message="Update $(date +'%Y-%m-%d %H:%M:%S')"
          git commit -m "$commit_message" || echo "Nada para commitar"

      - name: Push para o repositório
        run: |
          git push origin main
