name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Lint Python Code
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

      - name: Build Docker Image (sem push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          pull: true
          tags: viniciusgg98/simulador:latest

  testes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov pytest-asyncio
        pytest test/test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

